"""Koala API client — HTTP implementation with test_mode fallback.

In test_mode=True the client returns empty/stub results for reads and logs
writes without making network calls. In production mode (test_mode=False)
all methods make real HTTP calls to the Koala platform API.

github_file_url is a hard requirement on every write operation. The client
raises KoalaPreflightError immediately if it is missing or a placeholder,
independent of whether test_mode is active.

HTTP implementation uses stdlib urllib only — no third-party dependencies.
Authorization header format: "Authorization: <token>"

Environment variables
---------------------
KOALA_API_BASE_URL              override API base (default: https://koala.science/api/v1)
KOALA_API_TOKEN                 bearer token (required in live mode)
KOALA_ENDPOINT_ACTIVE_PAPERS    override /papers/ endpoint path
KOALA_ENDPOINT_PAPER            override /papers/{id} endpoint path
KOALA_ENDPOINT_COMMENTS         override /comments/paper/{id} endpoint path
KOALA_ENDPOINT_POST_COMMENT     override /comments/ POST endpoint path
"""

from __future__ import annotations

import json
import logging
import os
import time
import urllib.error
import urllib.parse
import urllib.request
from typing import Any, Dict, List, Optional

from .errors import KoalaAPIError, KoalaPreflightError, KoalaRateLimitError
from .models import Comment, Paper, PostCommentPayload, SubmitVerdictPayload

log = logging.getLogger(__name__)

_API_TIMEOUT_S: int = 15
_DEFAULT_API_BASE = "https://koala.science/api/v1"
_PLACEHOLDER_PREFIXES = ("TODO:", "test-artifact://")

# Substring unique to URLs generated by publish_*_artifact(test_mode=True).
# These must never reach a real external Koala write regardless of syntax.
_TEST_MODE_URL_MARKER = "github.com/test-mode-only/"

_MAX_RETRIES = 3
_RETRY_STATUS_CODES = frozenset({429, 500, 502, 503, 504})


def _require_github_url(github_file_url: str, context: str) -> None:
    if not github_file_url:
        raise KoalaPreflightError(
            f"{context}: github_file_url is required but was empty."
        )
    for prefix in _PLACEHOLDER_PREFIXES:
        if github_file_url.startswith(prefix):
            raise KoalaPreflightError(
                f"{context}: github_file_url is a placeholder ({github_file_url!r}). "
                "A real published URL is required for external actions."
            )


class KoalaClient:
    """Koala platform API client.

    Pass test_mode=True for offline development and unit tests — all read
    methods return empty results, all write methods log and return stubs.

    In production (test_mode=False), api_token (or KOALA_API_TOKEN env) must
    be non-empty and all methods make real HTTP calls to the Koala platform.
    """

    def __init__(
        self,
        api_base: Optional[str] = None,
        api_token: str = "",
        test_mode: bool = False,
        *,
        _retry_delay_s: float = 1.0,
    ) -> None:
        resolved_base = api_base or os.environ.get("KOALA_API_BASE_URL", _DEFAULT_API_BASE)
        self._base = resolved_base.rstrip("/")
        self._token = api_token or os.environ.get("KOALA_API_TOKEN", "")
        self._test_mode = test_mode
        self._retry_delay_s = _retry_delay_s

        if not test_mode and not self._token:
            raise ValueError(
                "api_token is required when test_mode=False. "
                "Provide it directly or set KOALA_API_TOKEN. "
                "Set test_mode=True for offline / unit-test use."
            )

    # ------------------------------------------------------------------
    # Endpoint configuration (overridable via env vars)
    # ------------------------------------------------------------------

    @property
    def _ep_active_papers(self) -> str:
        return os.environ.get("KOALA_ENDPOINT_ACTIVE_PAPERS", "/papers/")

    @property
    def _ep_paper(self) -> str:
        return os.environ.get("KOALA_ENDPOINT_PAPER", "/papers/{paper_id}")

    @property
    def _ep_comments(self) -> str:
        return os.environ.get("KOALA_ENDPOINT_COMMENTS", "/comments/paper/{paper_id}")

    @property
    def _ep_post_comment(self) -> str:
        return os.environ.get("KOALA_ENDPOINT_POST_COMMENT", "/comments/")

    # ------------------------------------------------------------------
    # Low-level HTTP
    # ------------------------------------------------------------------

    def _request(
        self,
        method: str,
        path: str,
        *,
        params: Optional[dict] = None,
        body: Optional[dict] = None,
    ) -> Any:
        """Make an authenticated HTTP request with retry/backoff. Returns parsed JSON."""
        url = f"{self._base}{path}"
        if params:
            filtered = {k: v for k, v in params.items() if v is not None}
            if filtered:
                url += "?" + urllib.parse.urlencode(filtered)

        data = json.dumps(body).encode() if body is not None else None
        headers: Dict[str, str] = {"Authorization": self._token}
        if data:
            headers["Content-Type"] = "application/json"

        last_exc: Exception = KoalaAPIError("unreachable")
        for attempt in range(_MAX_RETRIES):
            req = urllib.request.Request(url, data=data, headers=headers, method=method)
            try:
                with urllib.request.urlopen(req, timeout=_API_TIMEOUT_S) as resp:
                    raw = resp.read().decode("utf-8")
                    return json.loads(raw) if raw.strip() else {}
            except urllib.error.HTTPError as exc:
                body_bytes = exc.read()
                if exc.code in _RETRY_STATUS_CODES and attempt < _MAX_RETRIES - 1:
                    delay = self._retry_delay_s * (2 ** attempt)
                    log.warning(
                        "[KoalaClient] %s %s → %d; retrying in %.1fs (attempt %d/%d)",
                        method, path, exc.code, delay, attempt + 1, _MAX_RETRIES,
                    )
                    time.sleep(delay)
                    last_exc = KoalaRateLimitError(
                        f"Koala API rate limit: {method} {path} → {exc.code}"
                    ) if exc.code == 429 else KoalaAPIError(
                        f"Koala API error: {method} {path} → {exc.code}: "
                        f"{body_bytes[:200].decode('utf-8', errors='replace')}"
                    )
                    continue
                if exc.code == 429:
                    raise KoalaRateLimitError(
                        f"Koala API rate limit: {method} {path} → 429"
                    ) from exc
                raise KoalaAPIError(
                    f"Koala API error: {method} {path} → {exc.code}: "
                    f"{body_bytes[:200].decode('utf-8', errors='replace')}"
                ) from exc
            except Exception as exc:
                raise KoalaAPIError(
                    f"Koala API request failed: {method} {path}: {exc}"
                ) from exc
        raise last_exc

    def _extract_list(self, resp: Any) -> list:
        """Normalise paginated or direct-list API responses to a plain list."""
        if isinstance(resp, list):
            return resp
        if isinstance(resp, dict):
            for key in ("results", "data", "papers", "comments", "items"):
                if key in resp and isinstance(resp[key], list):
                    return resp[key]
        return []

    # ------------------------------------------------------------------
    # Read operations
    # ------------------------------------------------------------------

    def list_active_papers(self) -> List[Paper]:
        """List papers currently in review or verdict phase."""
        if self._test_mode:
            return []
        resp = self._request("GET", self._ep_active_papers, params={"status": "active", "limit": 100})
        return [Paper.from_api(d) for d in self._extract_list(resp)]

    def get_paper(self, paper_id: str) -> Optional[Paper]:
        """Fetch a single paper by ID. Returns None if not found (404)."""
        if self._test_mode:
            return None
        try:
            path = self._ep_paper.format(paper_id=paper_id)
            resp = self._request("GET", path)
            return Paper.from_api(resp) if resp else None
        except KoalaAPIError as exc:
            if "404" in str(exc):
                return None
            raise

    def list_comments(self, paper_id: str, *, limit: Optional[int] = None) -> List[Comment]:
        """Fetch all comments for a paper.

        Args:
            paper_id: target paper ID
            limit:    maximum number of comments to fetch.  When None, the value
                      of the KOALA_COMMENTS_LIMIT env var is used (default 500).
                      Increase this for high-volume papers; pagination is deferred.
        """
        if self._test_mode:
            return []
        path = self._ep_comments.format(paper_id=paper_id)
        effective_limit = (
            limit
            if limit is not None
            else int(os.environ.get("KOALA_COMMENTS_LIMIT", "500"))
        )
        resp = self._request("GET", path, params={"limit": effective_limit})
        return [Comment.from_api(d, paper_id) for d in self._extract_list(resp)]

    # ------------------------------------------------------------------
    # Write operations — github_file_url is a hard requirement
    # ------------------------------------------------------------------

    def post_comment(
        self,
        paper_id: str,
        body: str,
        github_file_url: str,
        thread_id: Optional[str] = None,
        parent_id: Optional[str] = None,
    ) -> str:
        """Post a comment on a paper. github_file_url is required.

        Args:
            paper_id:        target paper ID
            body:            comment body in markdown
            github_file_url: public transparency artifact URL (hard requirement)
            thread_id:       thread to reply into (None = new top-level thread)
            parent_id:       parent comment for a nested reply

        Returns:
            The created comment ID.

        Raises:
            KoalaPreflightError: if github_file_url is missing or a placeholder.
        """
        _require_github_url(github_file_url, f"post_comment(paper_id={paper_id!r})")
        if not self._test_mode and _TEST_MODE_URL_MARKER in github_file_url:
            raise KoalaPreflightError(
                f"post_comment(paper_id={paper_id!r}): test-mode artifact URL must not "
                f"reach a real external action: {github_file_url!r}"
            )

        payload = PostCommentPayload(
            paper_id=paper_id,
            body=body,
            github_file_url=github_file_url,
            thread_id=thread_id,
            parent_id=parent_id,
        )

        if self._test_mode:
            log.info("[test_mode] post_comment payload=%s", payload)
            return "test-comment-id"

        api_body: dict = {
            "paper_id": paper_id,
            "content_markdown": body,
            "github_file_url": github_file_url,
        }
        if parent_id is not None:
            api_body["parent_id"] = parent_id
        if thread_id is not None:
            api_body["thread_id"] = thread_id

        resp = self._request("POST", self._ep_post_comment, body=api_body)
        comment_id = resp.get("id") or resp.get("comment_id") if isinstance(resp, dict) else None
        if not comment_id:
            raise KoalaAPIError(
                f"post_comment: API response missing comment id for paper={paper_id!r}: {resp}"
            )
        log.info("[KoalaClient] posted comment id=%s on paper=%s", comment_id, paper_id)
        return str(comment_id)

    def submit_verdict(
        self,
        paper_id: str,
        score: float,
        cited_comment_ids: List[str],
        github_file_url: str,
        bad_contribution_agent_id: Optional[str] = None,
    ) -> bool:
        """Submit a verdict on a paper. github_file_url is required.

        Args:
            paper_id:                  target paper ID
            score:                     numeric score 0–10
            cited_comment_ids:         list of external comment IDs cited
            github_file_url:           public transparency artifact URL (hard requirement)
            bad_contribution_agent_id: optional agent ID for bad-contribution flag

        Returns:
            True on success (or test_mode).

        Raises:
            KoalaPreflightError: if github_file_url is missing or a placeholder.
        """
        _require_github_url(github_file_url, f"submit_verdict(paper_id={paper_id!r})")
        if not self._test_mode and _TEST_MODE_URL_MARKER in github_file_url:
            raise KoalaPreflightError(
                f"submit_verdict(paper_id={paper_id!r}): test-mode artifact URL must not "
                f"reach a real external action: {github_file_url!r}"
            )

        payload = SubmitVerdictPayload(
            paper_id=paper_id,
            score=score,
            cited_comment_ids=cited_comment_ids,
            github_file_url=github_file_url,
            bad_contribution_agent_id=bad_contribution_agent_id,
        )

        if self._test_mode:
            log.info("[test_mode] submit_verdict payload=%s", payload)
            return True

        api_body: dict = {
            "paper_id": paper_id,
            "content_markdown": "",  # caller must supply full verdict markdown separately
            "score": score,
            "github_file_url": github_file_url,
        }
        if bad_contribution_agent_id:
            api_body["bad_contribution_agent_id"] = bad_contribution_agent_id
        # TODO: accept content_markdown as parameter in Phase 5
        self._request("POST", "/verdicts/", body=api_body)
        log.info("[KoalaClient] submitted verdict for paper=%s score=%.1f", paper_id, score)
        return True
